version: '3'
services:
  npclassifier-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: npclassifier-dash
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
    ports:
    - "6541:5000"
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: npclassifier.ucsd.edu
      VIRTUAL_PORT: 6558
      LETSENCRYPT_HOST: npclassifier.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu
    restart: on-failure
    command: /app/run_server.sh
  
  npclassifier-tf-server:
    image: tensorflow/serving
    volumes:
        - ./Classifier/models_folder/models:/models
        - ./Classifier/models_folder/models.config:/models/models.config
    ports:
    - "8501:8501"
    - "8500:8500"
    restart: on-failure
    networks:
      - default
    command: --model_config_file=/models/models.config

networks:
  nginx-net:
    external:
      name: nginx-net